version: '2'
services:
  contaerp-app:
    image: contaerp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://contaerp-postgresql:5432/contaerp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://contaerp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://contaerp-elasticsearch:9200
    ports:
      - 8080:8080
  contaerp-postgresql:
    extends:
      file: postgresql.yml
      service: contaerp-postgresql
  contaerp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: contaerp-elasticsearch
