version: '2'
services:
  contaerp-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/contaerp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=contaerp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
